version: '3.8'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mu_sql_docker
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MuOnline.2026.Docker!
      - MSSQL_COLLATION=Modern_Spanish_CI_AS 
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: